apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ashutosh024/spe_backend
          ports:
            - name: http
              containerPort: 2000
          env:
            - name: MONGO
              value: "mongodb+srv://ashutosh024:aventador123@cluster0.fj7cclv.mongodb.net/?retryWrites=true&w=majority"
            - name: PORT
              value: "2000"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 2000
      targetPort: 2000
      # nodePort: 30001